name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config_timezone: India/Kolkata
          retries: 3
          retries_delay: 300
          config_display: large
          plugin_activity: yes
          plugin_activity_filter: issue, pr, release, fork, review, ref/create
          plugin_introduction: yes
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_colors: rainbow
          plugin_languages_limit: 4
          plugin_lines: yes
          plugin_lines_sections: base, repositories
          plugin_repositories: yes
          plugin_repositories_featured: vishwamartur/vishwamartur
          plugin_repositories_affiliations: owner, collaborator
          plugin_licenses: yes
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_ignored: explorer, gister, helper
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_isocalendar_duration: full-year
          plugin_traffic: yes
